---
include:
- "**/*.rb"
- "bin/*"
- "config.ru"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- .bundle/**/*
require: []
domains: []
plugins:
  - solargraph-rails
reporters:
- typecheck
max_files: 5000
