export ZSH=/Users/taylor/.oh-my-zsh
ZSH_THEME="panda"
plugins=(gitfast gpg-agent autojump bundler common-aliases ruby sublime sudo systemd)
DISABLE_UPDATE_PROMPT=true
KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh

#################################
## USER CONFIG BELOW THIS LINE ##
#################################

source "$HOME/.dotfiles/zshrc_shared"

