export ZSH=/home/taylor/.oh-my-zsh
ZSH_THEME="panda"
plugins=(gitfast autojump common-aliases sudo systemd)
KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh

#################################
## USER CONFIG BELOW THIS LINE ##
#################################

source "$HOME/.dotfiles/zshrc_shared"
